### ISSUE TITLE
RCS is a buggy Pink mess

### ISSUE THREAD

**Issue by RiccRacc** [Kari1407/Starship-Expansion-Project#29]
when i use the RCS it functions fine but its just these ugly pink lines let me know if its my fault or not and how to fix it if possible

**Comment by Fossilized4** [comment]
You need to be on the latest waterfall version. The RCS uses the relatively new volumetric style.

**Comment by RiccRacc** [comment]
is the newest waterfall available for 1.10.1?

**Comment by Fossilized4** [comment]
Yes

**Comment by RiccRacc** [comment]
i just checked and i already have latest version

**Comment by Fossilized4** [comment]
Then I would suggest reinstalling waterfall

**Comment by kochiBR** [comment]
do you use any decals on it ?

**Comment by Joepkock02** [comment]
Decals on what?

**Comment by Fossilized4** [comment]
The

**Comment by RiccRacc** [comment]
nah i dont have any decals on it

**Comment by Fossilized4** [comment]
jus

**Comment by kochiBR** [comment]
hm

**Comment by RiccRacc** [comment]
im reinstalling waterfall and seeing if it works

**Comment by Fossilized4** [comment]
kk

**Comment by RiccRacc** [comment]
reinstalling waterfall worked and i gotta say it looks good not sure if i want to use it in RSS though
but im definatly using waterfall for my stockalike game
