### ISSUE TITLE
docking isnt working( butt to butt)

### ISSUE THREAD

**Issue by RiccRacc** [Kari1407/Starship-Expansion-Project#31]
everytime i try to dock 2 starship together butt to butt they kinda pull them selves apart making it impossible to dock and i need to transfer fuel or my crew is dead i have a crewed ship with no fuel and a tanker with all the fuel i would need but they cant dock please help

**Comment by Fossilized4** [comment]
you

**Comment by RiccRacc** [comment]
what

**Comment by Fossilized4** [comment]
you should join the discord

**Comment by RiccRacc** [comment]
okay send me it

**Comment by Fossilized4** [comment]
https://discord.gg/CQzk9H84pr

**Comment by RiccRacc** [comment]
im in

**Comment by Fossilized4** [comment]
sure

**Comment by RiccRacc** [comment]
it was just being wierd lmao
