### ISSUE TITLE
Methane Venting not working

### ISSUE THREAD

**Issue by RiccRacc** [Kari1407/Starship-Expansion-Project#32]
okay so i set th fuels to methane and set the venting to methane but it dosent ever vent methane , so for me atleast venting only works with liquid fuel and oxy

**Comment by Fossilized4** [comment]
its easier to ask in discord

**Comment by RiccRacc** [comment]
i already did so im just posting this so maybe the devs can find a fix foor a later update

**Comment by SofieBrink** [comment]
Question when you were trying to vent methane when attached to the test stand or orbital pad from SLE?

**Comment by SofieBrink** [comment]
Closed due to inactivity
