### ISSUE TITLE
SSL-Issue on CKAN-Download

### ISSUE THREAD

**Issue by olsvse** [Kari1407/Starship-Expansion-Project#33]
Hello,

During the download with CKAN I get the following Error-Message:
Error downloading StarshipExpansionProject v1.0.1: Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
  at /builddir/build/BUILD/mono-6.12.0.122/external/boringssl/ssl/handshake_client.c:1132

Regards,
Oliver

**Comment by SofieBrink** [comment]
In the mean time you can still download SEP from either SpaceDock, or this github page!

**Comment by SofieBrink** [comment]
Closed due to inactivity
