### ISSUE TITLE
RO/RP1 compatibility

### ISSUE THREAD

**Issue by Matthias32** [Kari1407/Starship-Expansion-Project#35]
Hi, 

how do I have to use the "Extras" folder to have the parts in RO/RP1 available? I have installed the mod via ckan but the parts are not showing up in the editor. 

Thank you in advance. 

Best Regards
Matthias

**Comment by Fossilized4** [comment]
You need to drop the extras folder anywhere in gamedata

**Comment by Matthias32** [comment]
It worked! Thank you a lot!
