### ISSUE TITLE
RSS/RO MechJeb PVG Fails to launch, SH cluster engine issue

### ISSUE THREAD

**Issue by InfoTheGamer** [Kari1407/Starship-Expansion-Project#42]
When trying to launch any craft with the SH cluster engine as the first stage engine, PVG fails to launch and sets throttle to 0. This issue is reproducible and possibly due to the new behavior of the SH cluster engine. With this bug launching the full stack is not possible with automated means like PVG.

**Comment by InfoTheGamer** [comment]
This issue occurs in RSS/RO 1.12.3, with the newest SEP update and updated PVG.

**Comment by Kari1407** [comment]
Confirmed, PVG is not able to work with the cluster, but the other ascent guidances mechjeb brings are able to

**Comment by Kari1407** [comment]
Fixed by #43
