### ISSUE TITLE
Starship metal is black on launch pad

### ISSUE THREAD

**Issue by Brimmla** [Kari1407/Starship-Expansion-Project#48]
I've tried reinstalling it and reinstalling textures unlimited, but I can't think of anything else.

**Comment by IsaQuest** [comment]
For textures unlimited to correctly apply the shader, your graphical settings should be:

Reflection Texture Resolution: at least 256
Reflection Refresh Rate: at least Medium
Render Quality: at least Good

If you use Linux add these lines to the "Launch Options" on steam: -force-glcore42 -force-clamped
