### ISSUE TITLE
(RSS/RO 1.12.3) Starship Main body Radiator not working

### ISSUE THREAD

**Issue by shubhankar000** [Kari1407/Starship-Expansion-Project#51]
- The inbuilt radiator of the starship main body doesnt seem to affect the amount of boilof
- Boiloff is constant at 5-7 kg/hr, making refueling and interplanetary missions impossible
- 'Analytical Cooling' under the 'RF Boiloff' tab in the PAW menu of the starship while in orbit shows 0W
- Attaching external radiators seems to not work as intended. After about 15 days in orbit with 8 large radiators, the boiloff fell to 0.12kg/hr and never went below this amount
- Using RCS in orbit increases RF boiloff when boiloff is already very high, but using it after 15 days actually decreased boiloff below the 0.12kg/hr threshold

All this testing was done using 100 MLI layers. 
There are some mass issues with the MLI layers as well, upto 80 layers, dry mass of tank shows as 0t, above 80 it shoots to 26t

**Comment by Kari1407** [comment]
NGL I'm going to need some help to solve this, I don't know how the module works and neither how to get good values

**Comment by shubhankar000** [comment]
Wish I could help, but Im just a player. I have no idea how KSP modding works. At the most, I went into the .CFG file of the starship and did a ctrl+f for the radiators and multiplied all values by 10 and saved it. It did not make any difference unfortunately :(
I hope someone sees this and helps, maybe a legend like linuxgurugamer

**Comment by Franek800** [comment]
https://github.com/Kari1407/Starship-Expansion-Project/assets/66955040/d1adaa27-924c-472c-b5a7-222402c8c537

**Comment by SofieBrink** [comment]
> Nagranie.z.ekranu.2023-11-11.o.13.54.52.mov

This is a completely different issue, please open a new ticket if you still need support for it
