### ISSUE TITLE
Ship rcs plumes dont show up

### ISSUE THREAD

**Issue by lsamman** [Kari1407/Starship-Expansion-Project#52]
i have waterfall + realplume installed so not sure what the issue is

log: https://drive.google.com/file/d/1tNu4SPJ7HMQuKDq1BL9AEmjClVgbU_-J/view?usp=sharing

**Comment by SofieBrink** [comment]
The log doesn't tell anything and since i haven't heard others about this issue i'm marking it closed. Feel free to open a new ticket if the issue persists
