### ISSUE TITLE
Vesselview, DPAI and astrogator not working with the mod

### ISSUE THREAD

**Issue by Meatssauce** [Kari1407/Starship-Expansion-Project#53]
Nothing happens when you click the buttons that say A, B and C even when you have installed vesselview, DPAI and astrogator, and when the home page confirms that these mods have been installed.
It's supposed to switch Vesselview when I click on A, DPAI when I click on B and astrogator when I click on C.

**Comment by SofieBrink** [comment]
I'm expecting this issue  to be resolved when the new screens from Janus get propegated through. 
This is a likely issue due to  the duplication of the MFD's in the current IVA which will become irrelevent with that change
