### ISSUE TITLE
Starship and Superheavy tank parts don't have weight and no heat resistance

### ISSUE THREAD

**Issue by AncientColors** [Kari1407/Starship-Expansion-Project#54]
On RO/RP1 the bodies have no mass and only hold a 750t/150t of propellant. On LEO reentry, the upper stage also explodes due to heat. I tried changing the propellant values in my RO/RP1 config, but it had no effect.

**Comment by SofieBrink** [comment]
A KSP.log file would be much appreciated, Just this text alone makes it hard if not impossible to diagnose.

**Comment by AncientColors** [comment]
[KSP.log.zip](https://github.com/Kari1407/Starship-Expansion-Project/files/13461107/KSP.log.zip)

**Comment by SofieBrink** [comment]
I don't spot anything obvious and i don't have enough knowledge of the RO configs to help you further. @Kari1407 or @Anomalia2022 might be able to though

**Comment by Anomalia2022** [comment]
I will take a look at this log in a few hours. I don’t have a solid install of RO/RP1 to attempt a reproduction but I will give it my best shot to figure it out.

**Comment by AncientColors** [comment]
Thank you. I clean installed SEP and the configs 3 times, tried ckan and manually. Removal of the RP-1 core mod and it's configs had no effects either.

**Comment by Anomalia2022** [comment]
Could you also provide a fresh log from one of those installs? Would like to compare these. Another question is regarding the new Dev version of the mod, you didn’t accidentally download it perhaps when trying to freshly install your latest instance?

**Comment by Anomalia2022** [comment]
I think I have come to a potential solution looking into this. While this might not be it, I would like for you to move the RO-RP1 folder inside the Extra folder to StarshipExpansionProject/Patches folder. From the log I believe I am seeing the configs for RO/RP1 being loaded first because E in the load order comes before S and then the configs are being overwritten with the default fuel and resource values somehow. The configs in question that are responsible for RO don't actually have a AFTER[StarshipExpanionProject] flag and therefore can accidentally be loaded before the rest (lmfao)

**Comment by Anomalia2022** [comment]
The first one with Extras/etc are loaded about 2/4 into the log file while the other ones are loaded about 3/4 into the log file
![Screenshot 2023-11-26 110645](https://github.com/Kari1407/Starship-Expansion-Project/assets/62470335/6823d153-2732-488d-9b2e-e5e64277fe9d)
![Screenshot 2023-11-26 110515](https://github.com/Kari1407/Starship-Expansion-Project/assets/62470335/7c4163b4-5620-45da-a3d4-79410b486f42)

**Comment by Kari1407** [comment]
please try downloading the ro patches from github main branch,not release

**Comment by AncientColors** [comment]
Thanks guys! As @Anomalia2022 suggested, I put my RO/RP1 folder into the SEP Patches subfolder. Now the tanks weigh the right amount and hold their fuel as intended. Keep up the great work!
