### ISSUE TITLE
(KSP Steam 1.12.5 / SEP V2.0.3) No Engine Exhaust from Raptor Cluster

### ISSUE THREAD

**Issue by foulasign** [Kari1407/Starship-Expansion-Project#55]
The raptor engine cluster (all types and modes) isn't working properly. When using the raptor cluster, there is no exhaust. This is a problem ONLY with the engine cluster since the separate raptor engines have working exhaust textures. Another issue I'm having is that there are missing settings for all parts in my game, and not just in SEP, but I'm not sure how big an issue this is.
 
Points:
- No engine exhaust from raptor engine cluster (gimbal and throttle works)
- Waterfall textures for the raptor engine cluster are shown as having "0 effects" present
- Missing settings in all game parts, including SEP parts (an issue before I installed SEP)
![Screenshot 2023-11-24 135053](https://github.com/Kari1407/Starship-Expansion-Project/assets/151958297/a1c31f67-3eab-44ec-b1ab-c8f7de55b196)
![Screenshot 2023-11-24 140750](https://github.com/Kari1407/Starship-Expansion-Project/assets/151958297/3ac9bf95-97aa-403b-9df7-5cf9a7162ecd)

- I can change engine modes, indep throttle, etc... as action groups
![Screenshot 2023-11-24 140537](https://github.com/Kari1407/Starship-Expansion-Project/assets/151958297/c00c2f3f-57b0-4037-b91f-bca599906752)

- The console seems to be showing errors, but I'm not sure if they correlate to SEP
![Screenshot 2023-11-24 135300](https://github.com/Kari1407/Starship-Expansion-Project/assets/151958297/8a8d8474-f640-4649-9cdc-a4fc7b3378db)

other important info

- Gamedata folder
![Screenshot 2023-11-24 135630](https://github.com/Kari1407/Starship-Expansion-Project/assets/151958297/50b730d2-379a-4b1d-8d14-455f131295b6)

- Game Log (same session as when the screenshots were taken)
https://drive.google.com/file/d/1PgNYw1ceE9YXr6FUSTXp0mgkD5T0RRXx/view?usp=sharing

- SEP Raptor/Booster Cluster cfg file copy
 https://drive.google.com/file/d/1m_1L4rYkfHFb5vU5MObNgY5KIXdmYrse/view?usp=sharing

**Comment by SofieBrink** [comment]
Oh god, your install is really really messed up. Please give me the GameData/Waterfall/Versioning/Waterfall.version file

**Comment by foulasign** [comment]
> Oh god, your install is really really messed up. Please give me the GameData/Waterfall/Versioning/Waterfall.version file

https://drive.google.com/file/d/1Nsz_94Io0flPDUt7GWkEnaj9QopE4NxW/view?usp=sharing
darn github doesn't allow me to send .version files, so here's another google drive lol...
also the engine exhaust is a problem only with the booster cluster, but the separate raptors work fine (same with all other modded/stock engines)

**Comment by SofieBrink** [comment]
thanks, waterfall is shitting the bed and you're on a pretty old version so i recommend you remove waterfall entirely and reinstall the latest from [here](https://github.com/post-kerbin-mining-corporation/Waterfall/releases/latest). let me know if that works. if not i'd like another log

**Comment by foulasign** [comment]
> thanks, waterfall is shitting the bed and you're on a pretty old version so i recommend you remove waterfall entirely and reinstall the latest from [here](https://github.com/post-kerbin-mining-corporation/Waterfall/releases/latest). let me know if that works. if not i'd like another log

I've installed a few older mods that come with an outdated version of Waterfall, so I must have accidentally installed Waterfall though one of them. I'll see if it works thx.

**Comment by SofieBrink** [comment]
Yeah that’ll probably do it haha. Let me know how it all goes!

**Comment by foulasign** [comment]
> Yeah that’ll probably do it haha. Let me know how it all goes!
![Screenshot 2023-11-24 171039](https://github.com/Kari1407/Starship-Expansion-Project/assets/151958297/87348c10-c84a-445c-8749-3f87e69fa0b3)
![Screenshot 2023-11-24 171104](https://github.com/Kari1407/Starship-Expansion-Project/assets/151958297/fb624895-3c4b-4b0b-a12c-3eb33071fb49)
![Screenshot 2023-11-24 171147](https://github.com/Kari1407/Starship-Expansion-Project/assets/151958297/5076af0f-5577-4297-aa35-19f58c68da42)
![Screenshot 2023-11-24 171217](https://github.com/Kari1407/Starship-Expansion-Project/assets/151958297/77ad616b-a97e-4dca-b351-18a8ad1c678a)

It *kinda* works now, but the waterfall settings seem to be all janky. I have the latest versions of Waterfall, SEP, B9 Part Switch, and Module Manager. Here's the log.
https://drive.google.com/file/d/1x9Rd_TyVinuYe5XdL58i28QVcsCugZ-V/view?usp=sharing

**Comment by foulasign** [comment]
Reinstalled the waterfall patches, and that seemed to fix it. Thx

**Comment by SofieBrink** [comment]
Awesome sorry for not getting back to you on that last log, got a tad busy. 
Glad it works now!

**Comment by foulasign** [comment]
> Awesome sorry for not getting back to you on that last log, got a tad busy. Glad it works now!
It's good, thx for the help!
