### ISSUE TITLE
HotStageFX is not working 

### ISSUE THREAD

**Issue by ayana0409** [Kari1407/Starship-Expansion-Project#64]
HotStageFX doesn't work when I program the KAL-1000 for separation, but it still works when I separate using the spacebar

**Comment by Anomalia2022** [comment]
Sorry for late reply. This issue has been noted, but we cannot determine the issue without any further information regarding your install

**Comment by ayana0409** [comment]
I tried activating the booster's engine (not the exhaust valve) at the time of separation using the KAL-1000 and it worked. It seems like I didn't understand how HotStageFX and Vapor Cone worked before. Thank you
