### ISSUE TITLE
Using Hullcam can occasionally lock you camera view 

### ISSUE THREAD

**Issue by AllThingSpace33** [Kari1407/Starship-Expansion-Project#66]
Using the mod Hullcam VDS and FMRS with SEP can occasionally lock my camera view, not allowing me to right click move the camera around the booster or ship i dont currently have images but when i do i will add these to this post

**Comment by blueoriginal** [comment]
its annoying bug

**Comment by SofieBrink** [comment]
this feels like a hullcam bug report not a sep one, feel free to reopen if this is not the case
