### ISSUE TITLE
Flaps Doesent work

### ISSUE THREAD

**Issue by Luca296** [Kari1407/Starship-Expansion-Project#78]
Hi 
my problem is that my flaps dont move in any why.
Im placing them normaly in vab all roll pitch and yaw are active but when i launch it they dont move

**Comment by Cyberguru3** [comment]
Make sure to deploy the flaps, thats what allows to actuate.

**Comment by SofieBrink** [comment]
If that doesn’t work please provide us with your ksp.log file found in your root ksp directory

**Comment by SofieBrink** [comment]
> Waht you mean with deploy?

Exactly what it says, click the deploy button or add it to an action group

**Comment by Luca296** [comment]
> > Waht you mean with deploy?
> 
> Exactly what it says, click the deploy button or add it to an action group

No im so sorry!! I didnt saw the button befor!!
Bruh this is awkward

**Comment by SofieBrink** [comment]
All good, so it’s working now?

**Comment by Luca296** [comment]
Yes thanks again
