### ISSUE TITLE
Superheavy Clustered Engines are Pure reflective

### ISSUE THREAD

**Issue by NatoKerbal** [Kari1407/Starship-Expansion-Project#81]
![image](https://github.com/user-attachments/assets/ae56a738-04f2-493e-9003-40d2b71579c6)
This is on the dev Branch

**Comment by Kari1407** [comment]
please make sure you have **properly** installed the dev version by deleting the old folder and copying the updated version.
I ran into this issue _once_ and fixed it before pushing to dev.
If it still doesn't work feel free to reopen this issue with useful information like your log

![screenshot80](https://github.com/user-attachments/assets/aa850505-f946-4401-8d4a-0b419e12ed7d)
