### ISSUE TITLE
[Dev] Wonky effects on latest Dev

### ISSUE THREAD

**Issue by Alex1337Cool** [Kari1407/Starship-Expansion-Project#84]
### **Mod Version:**
Development

### **Build info:**

The newest Dev version from the 09.10.2024 (with the RO-Patches installed).

### **Describe the bug:**

1. I wanted to try the latest Dev build, but as soon as I spawned in all effects on the Ship/Booster went full bore with no apparent way of fixing them. 
2. Additionally when booting the game it now throws an error (see References).

### **Expected behavior:**

Well.. No party mode on Spawn.

### **Steps to reproduce:**

1. Install latest Dev
3. Build a Starship
4. Launch

### **References**

![Welp](https://github.com/user-attachments/assets/747d0dfc-d879-4e7e-9d6b-7759fce924e8)
(Also happens when RCS and throttle are off, its just on because of the screenshot).
![Warning on Startup](https://github.com/user-attachments/assets/17c6c1cf-03ac-45a5-80e2-5f9edb161241)

### **Additional info**

Installed Mods:

[ModList.txt](https://github.com/user-attachments/files/17350247/ModList.txt)

Log:

[KSP.log](https://github.com/user-attachments/files/17350229/KSP.log)

Craft File:

[Starship IFT-5.zip](https://github.com/user-attachments/files/17350257/Starship.IFT-5.zip)

This might have something to do with the latest Waterfall update which dropped around the same time as the latest Dev version.

Hope this helps :)

ps. Let's cross our fingers they Launch and make the catch tomorrow 🤞.

**Comment by Kari1407** [comment]
Fixed the missing transform on https://github.com/Kari1407/Starship-Expansion-Project/commit/4c5d2b7c10993bc017e9bc042ab08bac9c70f93b

The plumes are a result of the Waterfall 0.10.0, that brought some changes to the code and ended up creating a very specific issue with B9PS that seems to affect all but the raptors on SEP. there is a fix already, just wait for a new release (probably 0.10.3) or downgrade to 0.90 and you should be fine

**Comment by Alex1337Cool** [comment]
@Kari1407 thank you very much for the quick reply and fix 👍
